spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bfoj?characterEncoding=utf8&useSSL=true&serverTimezone=Asia/Shanghai
    #    username: root
    #    password: psd_116061yy
    username: javaee
    password: javaee
#    username: root
#    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  Thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    content-type: text/html
    mode: HTML5
    cache: false
  devtools:
    remote:
      restart:
        enabled: true
  http:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 200MB
mybatis:
  mapper-locations: classpath:*/mapper/*.xml
  type-aliases-package: com.bruteforces.demo.dao
server:
  port: 8080
  servlet:
    context-path: /


